// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgreiicqeirkyiwzgxky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtncmVpaWNxZWlya3lpd3pneGt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4ODI4NDAsImV4cCI6MjA2NjQ1ODg0MH0.D3LUhZVwrkHWlvyoXCA8Fax2PNg6A7gy9LmcdhSAwzA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);